version: '3'
services:
  web:
    # will build ./docker/web/Dockerfile
    build: ./project/djackets_vue
    ports:
     - "8080:8080"
    depends_on:
      - "db"
  db:
    # will build ./docker/db/Dockerfile
    build: ./project/djackets_django
    ports:
      - "8000:8000"